### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by iaz3** [iaz3/TCBot#53]
- [x] Improve trading
- [x] New installer
- [x] Improved error handling
- [x] Code Rewrite

**Comment by mgracer48** [comment]
how about -

- [ ] Mac support
im working on this at the moment

**Comment by mgracer48** [comment]
this is what i get when running the app i made compiling main.py
MacBook-Pro:tcbot mgracer48$ ./dist/Main.app/Contents/MacOS/Main
Feb 16 22:26:28  Main[29006] <Notice>: 2016-02-16 22:26:28.498 Main[29006:7394889] Main Error
Feb 16 22:26:31  Main[29006] <Notice>: Traceback (most recent call last):
Feb 16 22:26:31  Main[29006] <Notice>:   File "/Users/mgracer48/Desktop/tcbot/dist/Main.app/Contents/Resources/__boot__.py", line 400, in <module>
Feb 16 22:26:31  Main[29006] <Notice>:     _run()
Feb 16 22:26:31  Main[29006] <Notice>:   File "/Users/mgracer48/Desktop/tcbot/dist/Main.app/Contents/Resources/__boot__.py", line 394, in _run
Feb 16 22:26:31  Main[29006] <Notice>:     exec(compile(source, script, 'exec'), globals(), globals())
Feb 16 22:26:31  Main[29006] <Notice>:   File "/Users/mgracer48/Desktop/tcbot/Main.py", line 16, in <module>
Feb 16 22:26:31  Main[29006] <Notice>:     from lxml import html
Feb 16 22:26:31  Main[29006] <Notice>:   File "/usr/local/opt/python3/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/lxml/html/__init__.py", line 54, in <module>
Feb 16 22:26:31  Main[29006] <Notice>:     from .. import etree
Feb 16 22:26:31  Main[29006] <Notice>:   File "<frozen importlib._bootstrap>", line 969, in _find_and_load
Feb 16 22:26:31  Main[29006] <Notice>:   File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
Feb 16 22:26:31  Main[29006] <Notice>:   File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
Feb 16 22:26:31  Main[29006] <Notice>:   File "<frozen importlib._bootstrap>", line 634, in _load_backward_compatible
Feb 16 22:26:31  Main[29006] <Notice>:   File "/Users/mgracer48/Desktop/tcbot/dist/Main.app/Contents/Resources/__boot__.py", line 52, in load_module
Feb 16 22:26:31  Main[29006] <Notice>:     os.path.join(pkg_dir, fullname), ('', '', imp.PKG_DIRECTORY))
Feb 16 22:26:31  Main[29006] <Notice>:   File "/usr/local/opt/python3/Frameworks/Python.framework/Versions/3.5/lib/python3.5/imp.py", line 244, in load_module
Feb 16 22:26:31  Main[29006] <Notice>:     return load_package(name, filename)
Feb 16 22:26:31  Main[29006] <Notice>:   File "/usr/local/opt/python3/Frameworks/Python.framework/Versions/3.5/lib/python3.5/imp.py", line 216, in load_package
Feb 16 22:26:31  Main[29006] <Notice>:     return _load(spec)
Feb 16 22:26:31  Main[29006] <Notice>:   File "<frozen importlib._bootstrap>", line 692, in _load
Feb 16 22:26:31  Main[29006] <Notice>: AttributeError: 'NoneType' object has no attribute 'name'

**Comment by mgracer48** [comment]
luckily ik python so ill look into it

**Comment by iaz3** [comment]
Looks like a problem with lxml to me

**Comment by iaz3** [comment]
And, technically speaking, the python by itself would work on mac.

**Comment by iaz3** [comment]
And, i would never be able to support a mac build. I dont have a mac.

**Comment by mgracer48** [comment]
I would support it

**Comment by mgracer48** [comment]
got it working :D

**Comment by mgracer48** [comment]
ill make a .sh file
