### ISSUE TITLE
Mac support

### ISSUE THREAD

**Issue by iaz3** [iaz3/TCBot#55]
In theory, most, if not all, of it supports mac. The only problem is the paths.
I COULD get a paths library and let that handle it, but adds another source requirement.

- [ ] Add mac support and easy building.

Use [Travis CI?](https://docs.travis-ci.com/user/osx-ci-environment/)

**Comment by iaz3** [comment]
Help wanted to test on mac, when i get around to this.

@mgracer48

**Comment by mgracer48** [comment]
i got free travis ci

**Comment by mgracer48** [comment]
thing is i can only do it on repos i admin or own

**Comment by iaz3** [comment]
I would handle the Travis CI, you would test to make sure it works on mac.

After that i could setup the CI to build it for me on it's enviroment.

**Comment by mgracer48** [comment]
ooo

**Comment by mgracer48** [comment]
yep and thanks to my mac support ill add later u don't have to add any code

**Comment by mgracer48** [comment]
#56

**Comment by iaz3** [comment]
Wont fix. 
http://blog.roblox.com/2016/03/saying-goodbye-to-tickets/
