### ISSUE TITLE
Can't open any files

### ISSUE THREAD

**Issue by PoisedProgramar** [iaz3/TCBot#59]
I downloaded Python 3.5 and a windows thing, but nothing opens the .py file or the .md file. I'm using windows 7 64 bit if that helps.

**Comment by iaz3** [comment]
a .py file is essentially a text file.

You dont open a .py file, you run it in Python in the command prompt
The .md file is literally a text file, just with a different extension. the md stands for markdown.

If you cant figure out how to use Python, you shouldent be using the source.

Download the release.

**Comment by PoisedProgramar** [comment]
Download the release? This may sound stupid, I don't care, but what's the difference between the source and release? I'm too stupid to use command line, so I guess this isn't for me.

**Comment by iaz3** [comment]
Well, the release is a nice fancy EXE you can click and run like any other program

Also it Just Works(TM) no special fancy stuff to do to it.

Also it has all the required files.

It's literally just click and run.

**Comment by PoisedProgramar** [comment]
Where could I find the release? I've searched but I see nothing about github releases. Is the release on a different platform?

**Comment by iaz3** [comment]
![image](https://cloud.githubusercontent.com/assets/5275194/13198997/2cf02dc4-d7e6-11e5-9691-07eabadf694b.png)

**Comment by PoisedProgramar** [comment]
Holy fucking shit am I dumb. I was hoping for a shiny button, but I played myself.
