### ISSUE TITLE
TCBot still closing

### ISSUE THREAD

**Issue by Sentinel123** [iaz3/TCBot#60]
Hello. I am using the TCBot 3.01 and it still is crashing even after running as administrator. Do you have any solution that I can take? Thanks.

**Comment by iaz3** [comment]
If it's crashing you must be doing something wrong

What EXACTLY are you doing? WHEN does it crash? WHAT Operating system are you on? What is the error? and WHERE did you install it.

**Comment by Sentinel123** [comment]
Hi. I was opening the program and it randomly closed. It happens ever time I open it. I am on Windows 10. No error is coming, Installed it at C:\Program Files (x86)\Trade Currency Bot.
My mistake by crashing I meant randomly closing.

**Comment by iHeartx** [comment]
I have the same problem and when I opened it in cmd I got this
![error](https://cloud.githubusercontent.com/assets/17363869/13199110/e014b6ae-d813-11e5-9db0-50f0a0b2ccfd.png)

**Comment by iaz3** [comment]
Aha, i know the problem.

Fixed in 3.0.2 which will be released in a few minutes.

**Comment by Sentinel123** [comment]
ok thx

**Comment by iaz3** [comment]
Uploaded, you can go and download it now.

**Comment by iHeartx** [comment]
Thank you so much! (:
