### ISSUE TITLE
Keep losing Robux

### ISSUE THREAD

**Issue by PoisedProgramar** [iaz3/TCBot#63]
For some reason, I haven't profited at all. Instead, I just lost 35 Robux, which is kind of annoying. I'm pretty sure something is wrong with the new version. With version 2.02, I occasionally lost 1 or 2 robux, but with 3.04 I've just lost money.

**Comment by iaz3** [comment]
You shouldent be losing any money.

I've been running the latest version of my bot constantly since release, and havent lost any money.

I dont know what you're doing different, but it worksforme

![image](https://cloud.githubusercontent.com/assets/5275194/13208079/71e31330-d8e3-11e5-9f6a-2fced2a9d3da.png)

**Comment by iaz3** [comment]
Give me some more details.

What's the bot say on screen, for example?
Whats in the debug.log which should be located in
> %APPDATA%\Iaz3Programs\TCBot\Debug.log

Are you restarting it? You shouldent be closing it. That might make you lose money, but only because it doesnt know what you were doing last time.

The bot isnt meant to be closed. It's meant to stay on. All the time. Trading and making money. Turning it off confuses it. Dont do it.

**Comment by PoisedProgramar** [comment]
I believe that was the problem then. I closed the bot a couple times, and when starting up, would give me a trade like this: 

Getting 878 robux for x amount of tickets, but I had 903. 

As for errors, there's this: 

Error: KeyError: 'name=slice(0, None, None), domain=None, path=None'
Traceback(Send this to Iaz3 WITH Debug.log on your desktop):
  File "Console.py", line 21, in <module>
  File "Main.py", line 300, in <module>
  File "Main.py", line 269, in setup
  File "general.py", line 102, in LoadAccounts
  File "__init__.py", line 121, in post
  File "sessions.py", line 511, in post
  File "sessions.py", line 468, in request
  File "sessions.py", line 576, in send
  File "adapters.py", line 376, in send
  File "connectionpool.py", line 559, in urlopen
  File "connectionpool.py", line 353, in _make_request
  File "client.py", line 1083, in request
  File "client.py", line 1128, in _send_request
  File "client.py", line 1079, in endheaders
  File "client.py", line 913, in _send_output
  File "client.py", line 885, in send
  File "ssl.py", line 886, in sendall
  File "cookies.py", line 287, in __getitem__
  File "cookies.py", line 345, in _find_no_duplicates


I skipped many trades, but from my starting robux and ending robux you can see I lost them along the way:

Robux: 903
Tickets: 31


BuxWant: 898
TixCost: 15469
BuxProfit: -5
TixProfit: 5
LastBux: 903
LastTix: 31



BuxWant: 898
TixCost: 15474
BuxProfit: -5
TixProfit: 0
LastBux: 903
LastTix: 31



BuxWant: 897
TixCost: 15459
BuxProfit: -6
TixProfit: 15
LastBux: 903
LastTix: 31


BuxWant: 888
TixCost: 15349
BuxProfit: -13
TixProfit: 0
LastBux: 901
LastTix: 15365



BuxWant: 887
TixCost: 15333
BuxProfit: -14
TixProfit: 16
LastBux: 901
LastTix: 15365


As you can see, I'm just losing Robux(the omitted logs, which are hundreds, are just the same thing over and over with slightly different profit amounts), and for some reason, the trades go through.

**Comment by iaz3** [comment]
As you can see [here](https://github.com/iaz3/TCBot/blob/master/Main.py#L158) in the code, it prints that regardless of whether it makes a trade or not. it's there for debugging. For ME to debug. thats why it's a debug log.

And [here](https://github.com/iaz3/TCBot/blob/master/Main.py#L162) you can see one of the FIRST things it checks is that buxProfit is MORE than 0. Anything negative is LESS than zero. it wont make those trades.

You'll know if it made a trade by the slightly different message printed [here](https://github.com/iaz3/TCBot/blob/master/Main.py#L165)

In all possible cases for making a trade, you have to be getting more than 0 robux. 

As for the KeyError, well, WorksForMe. I've never gotten it, and i cant see what could be causing it. The relevant line of code is [here](https://github.com/iaz3/RbxAPI/blob/master/RbxAPI/__init__.py#L125) in RbxAPI

**Comment by iaz3** [comment]
As for closing the bot that, i dont support doing that.

Version 3.0 is intended to be run constantly, all the time. Closing it and opening again will confuse it.

Now, it DOES have some MINIMAL checks for this, but nothing foolproof. As you can see [here](https://github.com/iaz3/TCBot/blob/master/Main.py#L122)
it sets the last money you had to whatever it currently is.

At the very least, you wont end up with less than you had when you started it.

In previous versions there was a config.ini file, which saved the Last tix and bux values and read them when you restarted the bot. But this caused a ton of OTHER issues.

The problem, you see, is that while the bot was closed anything could have happened. You could have spent money, gotten money, currently trading money, who knows? And i found no reliable way to save and set the values.

If i just blindly trusted nobody changed their money, or got any more, then the values could be set LOWER than what you have, and make you lose money.

Or if you spent money, it could be set too high and never make any trades ever again.(This was actually a common issue with the old version 2.x series and The solution was to just delete the config file so it would start over.)

Or something else could have happened to it and who knows.

So i opted to just tell people not to close it. It CAN run 24/7 now(i've been running it for days nonstop and it hasent crashed) so there isnt any reason not to. Run it and wait, and you'll get money. (Though, spending it might confuse it. I'm not sure. But hey, the point is to not spend it. Not until you're rich at least)

And, this is Top Secret, but i MIGHT be releasing an online version of the bot that can run 24/7 for them. I have a website, iaz3.com, so maybe i could set it up so people can login there and have the site run the bot for them. I've had issues with getting it to work on a webserver though, not to mention i would need to code an admin control panel for the bot so you can stop it, or login, or log out. Or see trades. and honestly i'm lazy. Dont expect it any time soon.

**Comment by PoisedProgramar** [comment]
So, you recommend I leave my PC on 24/7? That doesn't seem good for my potato pc.

**Comment by iaz3** [comment]
How would it not be good? Computers are fine to leave on 24/7 unless theres something wrong with them or you do something wrong

I leave mine on.

**Comment by PoisedProgramar** [comment]
So, just curious, but why can't the bot just look at the amount of money you have at that instant? What problems does that cause, and why is using that not reliable? Is fetching the amount of money you  have going to interrupt a trade? If, let's say, a 200 R$ trade is going through, and once 100 R$ is traded, I spend those 100 R$, won't the trade just keep going? After all, the bot only looks for and initiates the trade.

**Comment by iaz3** [comment]
It DOES fetch the amount of money you have when you start it.
Thats what it currently does
No one said that wasent reliable.

**Comment by PoisedProgramar** [comment]
> You could have spent money, gotten money, currently trading money, who knows? And i found no reliable way to save and set the values.

Those values are what I was referring to. Instead of trying to track those, wouldn't it be the same(but easier) to simply fetch the R$ value you have and have some sort of system where it refreshes upon starting and while executing a trade.

**Comment by iaz3** [comment]
I feel like you're poorly describing what it already does.
