### ISSUE TITLE
Opens, then closes. Windows 10

### ISSUE THREAD

**Issue by C-arnifex** [iaz3/TCBot#66]
Help? When I open it just closes right after

**Comment by iaz3** [comment]
Details?

You ARE using the EXE, right?

**Comment by C-arnifex** [comment]
Yeah

**Comment by C-arnifex** [comment]
It just opens, show somes text and it just closes fast. It opens a cmd prompt, then closes. I have python installed

**Comment by C-arnifex** [comment]
FIXED, I was using 32 bit thanks!

**Comment by iaz3** [comment]
You dont need python installed to use this, if you're using it correctly. It comes with python.

**Comment by iaz3** [comment]
So how did you fix it? What was the problem.
