### ISSUE TITLE
ROBLOX Discontinuing Tickets. TCBot useless starting 4/13/2016

### ISSUE THREAD

**Issue by iaz3** [iaz3/TCBot#68]
http://blog.roblox.com/2016/03/saying-goodbye-to-tickets/

ROBLOX is removing the Trade Currency, and the Tickets. in 30 days

Starting April 13th, the TCBot will be useless.

I recommend **NOT** Running the bot

**Comment by PoisedProgramar** [comment]
Well, it was good while it lasted. Many thanks for keeping this alive, it's earned me over 1,000 Robux.

**Comment by iaz3** [comment]
Wow, awesome

Sadly i've never made much robux with it, never had enough to start with.
Ironic, isnt it? Made a TCBot, others got tons of robux with it, but i myself never did

**Comment by PoisedProgramar** [comment]
What would happen if you ran the TC Bot after trade currency was removed? Would you just get an error, or could it actually mess with your money?

**Comment by iaz3** [comment]
Probably error.

It's extremely unlikely that ROBLOX will just remove the TC page, but still allow all the requests and what not to magically get rid of your money.

**Comment by Sentinel123** [comment]
bro i just want to say thanks so much for making this man it was flawless and it sucks that roblox is removing tixs :(
